[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['rm -rf node_modules', 'npm install --legacy-peer-deps']

[phases.build]
cmds = ['chmod +x node_modules/.bin/*', 'npm run build']

[start]
cmd = 'npx serve -s build -l $PORT'